// Keyword strategy reference for Moonsmoke Network content planning and paid campaigns.
// Prioritised by: (1) commercial + affiliate, (2) informational + affiliate,
// (3) commercial without affiliate (future opportunity).

export interface KeywordTarget {
  keyword: string;
  intent: "informational" | "commercial" | "transactional";
  difficulty: "low" | "medium" | "high";
  targetUrl: string;
  site: "ph" | "ce" | "fh" | "lt";
  hasAffiliate: boolean;
  notes?: string;
}

export const keywordTargets: KeywordTarget[] = [
  // =====================================================================
  // TIER 1 — Commercial intent + affiliate link (highest priority)
  // =====================================================================
  {
    keyword: "best ai writing tools 2026",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/tools/category/writing/",
    site: "ph",
    hasAffiliate: true,
    notes: "Jasper AI + Grammarly affiliate links",
  },
  {
    keyword: "jasper ai review",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/jasper-ai/",
    site: "ph",
    hasAffiliate: true,
    notes: "Jasper affiliate link active",
  },
  {
    keyword: "grammarly review 2026",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/tools/grammarly/",
    site: "ph",
    hasAffiliate: true,
    notes: "Grammarly affiliate link active",
  },
  {
    keyword: "jasper ai vs grammarly",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/compare/jasper-ai-vs-grammarly/",
    site: "ph",
    hasAffiliate: true,
    notes: "Both have affiliate links",
  },
  {
    keyword: "best seo tools 2026",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/blog/best-seo-tools-2026/",
    site: "ce",
    hasAffiliate: true,
    notes: "Semrush + Ahrefs + SurferSEO affiliate links",
  },
  {
    keyword: "semrush review",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/tools/semrush/",
    site: "ce",
    hasAffiliate: true,
    notes: "Semrush affiliate link active",
  },
  {
    keyword: "ahrefs vs semrush",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/blog/best-seo-tools-2026/",
    site: "ce",
    hasAffiliate: true,
    notes: "Both have affiliate links; high-volume keyword",
  },
  {
    keyword: "surfer seo review",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/surfer-seo/",
    site: "ce",
    hasAffiliate: true,
    notes: "SurferSEO affiliate link active",
  },
  {
    keyword: "best vpn remote workers",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/blog/best-vpn-remote-workers-2026/",
    site: "ph",
    hasAffiliate: true,
    notes: "NordVPN affiliate via Awin (aff_id 142338); Impact offer_id 15",
  },
  {
    keyword: "best web hosting 2026",
    intent: "commercial",
    difficulty: "high",
    targetUrl: "/tools/category/hosting/",
    site: "ph",
    hasAffiliate: true,
    notes: "SiteGround afcode 758135cea38bbc354897accd3183d9ff + Cloudways affiliate",
  },
  {
    keyword: "descript review",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/descript/",
    site: "ph",
    hasAffiliate: true,
    notes: "Descript affiliate link active",
  },
  {
    keyword: "canva ai vs midjourney",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/compare/canva-ai-vs-midjourney/",
    site: "ph",
    hasAffiliate: true,
    notes: "Canva affiliate link active",
  },

  // =====================================================================
  // TIER 2 — Informational intent + affiliate link
  // =====================================================================
  {
    keyword: "chatgpt vs claude which is better",
    intent: "informational",
    difficulty: "high",
    targetUrl: "/blog/chatgpt-vs-claude-which-ai-assistant/",
    site: "ph",
    hasAffiliate: true,
    notes: "Blog includes affiliate tool links",
  },
  {
    keyword: "free ai tools for freelancers",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/free-ai-tools-for-freelancers/",
    site: "ph",
    hasAffiliate: true,
    notes: "Blog contains multiple affiliate tool links",
  },
  {
    keyword: "ai workflow automation guide",
    intent: "informational",
    difficulty: "low",
    targetUrl: "/blog/ai-workflow-automation-guide/",
    site: "ph",
    hasAffiliate: true,
    notes: "Zapier affiliate link embedded",
  },
  {
    keyword: "chatgpt for seo",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/chatgpt-for-seo-complete-guide/",
    site: "ce",
    hasAffiliate: true,
    notes: "Post links to Semrush & SurferSEO (affiliate)",
  },
  {
    keyword: "ai content writing seo strategy",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/ai-content-writing-seo-strategy/",
    site: "ce",
    hasAffiliate: true,
    notes: "Embedded SurferSEO affiliate link",
  },
  {
    keyword: "best ai budgeting apps 2026",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/best-ai-budgeting-apps-2026/",
    site: "fh",
    hasAffiliate: false,
    notes: "No affiliate yet but strong commercial intent; high opportunity",
  },
  {
    keyword: "how to use chatgpt personal finance",
    intent: "informational",
    difficulty: "low",
    targetUrl: "/blog/chatgpt-personal-finance-guide/",
    site: "fh",
    hasAffiliate: false,
    notes: "Long-tail; low competition; educate-then-convert funnel",
  },
  {
    keyword: "fireflies ai vs otter ai",
    intent: "informational",
    difficulty: "low",
    targetUrl: "/compare/fireflies-ai-vs-otter-ai/",
    site: "ph",
    hasAffiliate: true,
    notes: "Comparison page; Fireflies affiliate potential",
  },
  {
    keyword: "notion ai vs chatgpt for work",
    intent: "informational",
    difficulty: "low",
    targetUrl: "/blog/notion-ai-vs-chatgpt-work/",
    site: "ph",
    hasAffiliate: true,
    notes: "Existing blog post with tool links",
  },

  // =====================================================================
  // TIER 3 — Commercial intent, no affiliate yet (future opportunity)
  // =====================================================================
  {
    keyword: "best ai meeting transcription tools",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/category/meeting-assistants/",
    site: "ph",
    hasAffiliate: false,
    notes: "Fireflies, Otter — no affiliate links yet; partnership opportunity",
  },
  {
    keyword: "ai tax tools freelancers 2026",
    intent: "commercial",
    difficulty: "low",
    targetUrl: "/blog/ai-tax-tools-freelancers-2026/",
    site: "fh",
    hasAffiliate: false,
    notes: "TurboTax affiliate program available; apply",
  },
  {
    keyword: "best ai investing tools beginners",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/blog/ai-investing-tools-beginners-guide/",
    site: "fh",
    hasAffiliate: false,
    notes: "Wealthfront / Betterment affiliate potential",
  },
  {
    keyword: "ramp vs brex vs divvy",
    intent: "commercial",
    difficulty: "low",
    targetUrl: "/blog/ramp-vs-brex-vs-divvy-ai-expense-cards-compared/",
    site: "fh",
    hasAffiliate: false,
    notes: "Ramp referral program available",
  },
  {
    keyword: "ai contract analysis tools",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/blog/harvey-vs-spellbook-vs-ironclad/",
    site: "lt",
    hasAffiliate: false,
    notes: "High commercial intent; enterprise affiliate potential",
  },
  {
    keyword: "legal tech tools for solo attorneys",
    intent: "commercial",
    difficulty: "low",
    targetUrl: "/blog/ai-tools-small-law-firms/",
    site: "lt",
    hasAffiliate: false,
    notes: "Low competition niche; review tools page links",
  },
  {
    keyword: "ai e-discovery tools review",
    intent: "commercial",
    difficulty: "low",
    targetUrl: "/blog/ai-e-discovery-cut-review-time/",
    site: "lt",
    hasAffiliate: false,
    notes: "Everlaw / Relativity affiliate potential",
  },
  {
    keyword: "ai legal research westlaw vs lexisnexis",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/blog/ai-legal-research-westlaw-vs-lexisnexis/",
    site: "lt",
    hasAffiliate: false,
    notes: "CoCounsel affiliate potential via Thomson Reuters",
  },
  {
    keyword: "keyword research guide beginners",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/keyword-research-guide/",
    site: "ce",
    hasAffiliate: true,
    notes: "Links to Semrush/Ahrefs affiliate tools",
  },
  {
    keyword: "technical seo audit checklist",
    intent: "informational",
    difficulty: "medium",
    targetUrl: "/blog/technical-seo-checklist/",
    site: "ce",
    hasAffiliate: true,
    notes: "References paid tools with affiliate links",
  },
  {
    keyword: "schema markup generator free",
    intent: "transactional",
    difficulty: "low",
    targetUrl: "/tools/schema-markup-generator/",
    site: "ce",
    hasAffiliate: false,
    notes: "Free tool drives organic traffic; upsell to paid SEO tools",
  },
  {
    keyword: "meta tag generator seo",
    intent: "transactional",
    difficulty: "low",
    targetUrl: "/tools/meta-tag-generator/",
    site: "ce",
    hasAffiliate: false,
    notes: "Free tool; captures traffic for retargeting",
  },
  {
    keyword: "automate small business finances ai",
    intent: "informational",
    difficulty: "low",
    targetUrl: "/blog/automate-small-business-finances-ai/",
    site: "fh",
    hasAffiliate: false,
    notes: "QuickBooks AI affiliate potential; high conversion intent",
  },
  {
    keyword: "ai accounting software review",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/quickbooks-ai/",
    site: "fh",
    hasAffiliate: false,
    notes: "QuickBooks + Xero affiliate programs available",
  },
  {
    keyword: "legal document automation tools",
    intent: "commercial",
    difficulty: "low",
    targetUrl: "/blog/legal-document-automation-2025/",
    site: "lt",
    hasAffiliate: false,
    notes: "Ironclad / Spellbook partnership opportunity",
  },
  {
    keyword: "best ai design tools 2026",
    intent: "commercial",
    difficulty: "medium",
    targetUrl: "/tools/category/design/",
    site: "ph",
    hasAffiliate: true,
    notes: "Canva affiliate link active",
  },
];
